### ISSUE TITLE
Make the deposit (mint) confirmation clearer to understand

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#172]
On the last step of my test transfer, I was redirected to the wallet page. 

- The Bridge should say something like "We're directing you to your wallet to confirm this transaction"
- The wallet screen should somehow indicate that I'm interacting with my wallet
- I'm being asked to "Allow" on the wallet page. (Allow what?)
- The confirmation screen after allowing says, "Successful transfer of 0.06 NEAR!" I thought I was transferring ALCX?

![](http://d.dafacto.com/gjl59d+)

**Comment by paouvrard** [comment]
@dafacto Closing this issue as the 1st point has been addressed. Remaining points are NEAR Wallet improvements.
