### ISSUE TITLE
Bug? — Blank screen after transfer approval

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#189]
After approving the transfer of my BAL tokens, I wasn't redirected to a wallet confirmation, and the screen was blank. Working with Pierre, this was resolved by removing the transaction hash manually from the current screen URL.

![](http://d.dafacto.com/PELE2L+)

**Comment by mikedotexe** [comment]
This has happened to me, too. For me it's also happening after I have deployed a factory contract for a new pair, GUSD. My URL is https://ethereum.bridgetonear.org/?transactionHashes=BjTMQQV5HYwbBtjh2Ueqksi8HrVKKsmM2qZEn6TERsZM
I'm on Brave with "shields down."

**Comment by mikedotexe** [comment]
I believe this was after the "Deposit" part:

![Kapture 2021-04-13 at 7 06 50](https://user-images.githubusercontent.com/1042667/114566561-44641780-9c27-11eb-9d7f-0166295d0d21.gif)
