### ISSUE TITLE
Use normal token names in the user interface, instead of nToken

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#190]
- Deposit 1.7 BAL in NEAR (elsewhere in the progress status?)
- Token selector list on NEAR site

![](http://d.dafacto.com/1DrSCX+)

![](http://d.dafacto.com/nXzc10+)

**Comment by paouvrard** [comment]
Duplicate with https://github.com/aurora-is-near/rainbow-bridge-frontend/issues/163
