### ISSUE TITLE
Connected network not displayed correctly on mobile

### ISSUE THREAD

**Issue by paouvrard** [aurora-is-near/rainbow-bridge-frontend#202]
![image](https://user-images.githubusercontent.com/29397451/114115387-aec24280-991d-11eb-9955-230f48c2088f.png)

**Comment by corwinharrell** [comment]
@paouvrard happy to take this on. I'll request your review once I can think of something that works and have opened a PR 👍

**Comment by corwinharrell** [comment]
@paouvrard don't think I'll actually have the bandwidth to take this on at the moment (It's a bit more involved than I anticipated), but here's what I propose: On mobile, we move the network selector out of the nav and display it at 100% width directly underneath. On desktop, it should remain in the header. Not sure how you want to organize the logic around how to display this, but feel free to ping me for a review to double check how it looks/feels in that location.

<img width="704" alt="Screen Shot 2021-04-16 at 12 51 29 PM" src="https://user-images.githubusercontent.com/5934188/115058161-ecd9dc00-9eb2-11eb-9e1a-effc7f52fa1d.png">

**Comment by paouvrard** [comment]
@corwinharrell I'm not sure how that would look under the warning banner ..
What do you think of putting it over the home bridge icon ?
![image](https://user-images.githubusercontent.com/29397451/115402409-5b59c980-a226-11eb-8aab-d0da57a900d3.png)

**Comment by corwinharrell** [comment]
@paouvrard do we have any idea how long the ledger warning banner is going to persist? From my understanding it is a temporary issue, but I don't have context on when it will be addressed.

**Comment by paouvrard** [comment]
@corwinharrell it can be long since the ledger app would need to be reviewed and approved (weeks ?)

**Comment by corwinharrell** [comment]
> What do you think of putting it over the home bridge icon ?

@paouvrard Sure for mobile I think this is fine for now 👍
