### ISSUE TITLE
Use archival rpc to restore transactions.

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge-frontend#232]
Transactions from NEAR to Ethereum takes ~16 hours to land, and it is common user waits more than that. After 5 epoch passes, these transactions are garbage collected so regular RPC will not work to restore them. Let's use instead archival rpc to this end: https://archival-rpc.mainnet.near.org/

**Comment by paouvrard** [comment]
@mfornet If it ok to use this archival rpc as the main rpc for all queries ?

**Comment by mfornet** [comment]
> @mfornet If it ok to use this archival rpc as the main rpc for all queries ?

Yes, it is. In the moment it stops to be ok, we probably should run a dedicated archival node only for the bridge.

**Comment by paouvrard** [comment]
https://github.com/aurora-is-near/rainbow-bridge-frontend/pull/222/commits/4052d3421478d217f869b92c525de83e08c077eb
