### ISSUE TITLE
Add a notifications to the user about the cost of unlocking tokens

### ISSUE THREAD

**Issue by djsatok** [aurora-is-near/rainbow-bridge-frontend#234]
Multiple users are experiencing the problem of high Ethereum fees during the finalisation of the withdraw to Ethereum. As a result, they want to stop the transfer and return the tokens back to their NEAR Wallet.

We need to add two notifications in the interface to address this issue:
1. An approximate cost (in USD) for the finalisation of the transfer
2. Information that the transfer cannot be canceled, once it is started

This might be important for Aurora bridge too.

CC: @dafacto

**Comment by mfornet** [comment]
Similar to #229
