### ISSUE TITLE
Use NEAR instead of $NEAR in the UI

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#250]
This is seen in several places so I guess a global search/replace might be needed.

![](http://d.dafacto.com/6by5BU+)

**Comment by paouvrard** [comment]
My understanding is that `$NEAR` differentiates the native NEAR token from `NEAR` the protocol as in `Deposit 20 $NEAR in NEAR`

**Comment by dafacto** [comment]
If `$NEAR` is the only token that we prefix the `$` on, then I think I'd prefer to just say, `Deposit 20 NEAR in NEAR` to be consistent with how we treat all other tokens. I can't imagine it would create major confusion, even though I agree there's a tiny bit of cognitive friction the first time you see it.

**Comment by paouvrard** [comment]
https://github.com/aurora-is-near/rainbow-bridge-client/pull/30/commits/9459da74422533d86a4f005a8322fe99129c09c1
