### ISSUE TITLE
Can we add a MetaMask icon here?

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#251]
It would be great to add a MetaMask icon next to the trash can icon, that when clicked, adds the NEAR token to the MetaMask asset list.

![](http://d.dafacto.com/6by5BU+)

**Comment by paouvrard** [comment]
I think it would be better to make a PR here: https://github.com/MetaMask/contract-metadata to register NEAR as an known erc20 token to metamask.

Most holders or NEAR on Ethereum will probably get it through Uniswap and not via this interface.
Adding a button like this would be Metamask specific and not work for walletConnect wallets.

**Comment by dafacto** [comment]
Right, that makes sense. Closing issue.
