### ISSUE TITLE
Redirected to wrong screen after NEAR confirmation

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#257]
I setup a NEAR to Ethereum test transfer of 5 NEAR. After confirming the transaction in the NEAR wallet, I was redirected to this screen:

![](http://d.dafacto.com/wJZ60V+)

**Comment by dafacto** [comment]
Returning to the home screen, I discovered that my NEAR transaction failed:

![](http://d.dafacto.com/gcbgMv+)

**Comment by paouvrard** [comment]
https://github.com/aurora-is-near/rainbow-bridge-client/issues/38

**Comment by paouvrard** [comment]
Fixed here: https://github.com/aurora-is-near/rainbow-bridge-client/pull/30/commits/d965fc4cd7cbfc414b6ba75dc005c3ea8b5fa879
