### ISSUE TITLE
Register account on NEP-141 before making sending tokens from Aurora to NEAR

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge-frontend#323]
While sending tokens from Aurora to NEAR, Bridge App must make sure the receiver account is registered on the NEP-141 account. If it is not registered, registration should happen first.

To check if an account is registered use method `storage_balance_of` directly on the NEP-141 account contract.

```rust
    fn storage_balance_of(&self, account_id: ValidAccountId) -> Option<StorageBalance>;
```

To register an account use method `storage_deposit` directly on the NEP-141 account contract. 

```rust
    // if `registration_only=true` MUST refund above the minimum balance if the account didn't exist and
    //     refund full deposit if the account exists.
    fn storage_deposit(
        &mut self,
        account_id: Option<ValidAccountId>,
        registration_only: Option<bool>,
    ) -> StorageBalance;
```

`0.0125` NEAR tokens should be attached to make this registration in general, but to accurately determine this number use the method `storage_balance_bounds`.

```rust
fn storage_balance_bounds(&self) -> StorageBalanceBounds;
```

**Comment by paouvrard** [comment]
Fixed here: https://github.com/aurora-is-near/rainbow-bridge-frontend/pull/324
