### ISSUE TITLE
It takes a long time to wNear asset appear in https://aurora.bridgetonear.org/ after transferred Near from Near to Aurora

### ISSUE THREAD

**Issue by TienNLN** [aurora-is-near/rainbow-bridge-frontend#343]
Last night I transferred Near from Near to Aurora but I can't see any assets available in Aurora's assets (both wNear and Near). This morning the wNear appears correctly. I don't know exactly how long it takes, but I think that's not good if it does not appear instantly when transferring assets.

**Comment by mfornet** [comment]
This was a problem with the RPC not being responsive most likely. Tx happens instantaneously.
